from typing import Protocol, Self, TypeAlias, TypeGuard

NumberLike: TypeAlias = int | float


class ValueLike(Protocol):
    def __add__(self, other: Self, /) -> Self: ...
    def __radd__(self, other: Self, /) -> Self: ...
    def __sub__(self, other: Self, /) -> Self: ...
    def __rsub__(self, other: Self, /) -> Self: ...
    def __mul__(self, other: Self, /) -> Self: ...
    def __rmul__(self, other: Self, /) -> Self: ...
    def __truediv__(self, other: Self, /) -> Self: ...
    def __rtruediv__(self, other: Self, /) -> Self: ...
    def __pow__(self, other: Self, /) -> Self: ...
    def __rpow__(self, other: Self, /) -> Self: ...
    def __neg__(self, /) -> Self: ...
    def __abs__(self, /) -> Self: ...


def is_number_like(value: object) -> TypeGuard[NumberLike]:
    return isinstance(value, (int, float))
